### ISSUE TITLE
Plugin crash when trying to import existing cluster into terraform

### ISSUE THREAD

**Issue by devinchristianson** [cockroachdb/terraform-provider-cockroach#131]
When trying to import an existing cluster into terraform, the plugin crashed due to a memory panic (see error below).

The terraform import command run was `terraform import module.databases.cockroach_cluster.main_cluster <cluster uuid, copied from URL bar of console>`

Please let me know if you need any further information on my configuration, or have any other questions.

```╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain
│ more details.
╵


Stack trace from the terraform-provider-cockroach_v0.6.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xb33d20]

goroutine 27 [running]:
github.com/cockroachdb/terraform-provider-cockroach/internal/provider.loadClusterToTerraformState(0xc00027e0f0, 0xc00029c360, 0xc00029c360)
        github.com/cockroachdb/terraform-provider-cockroach/internal/provider/cluster_resource.go:790 +0x4a0
github.com/cockroachdb/terraform-provider-cockroach/internal/provider.(*clusterResource).Read(0xc000124b70, {0xe9d680, 0xc0004dd8f0}, {{{{0xea11a8, 0xc000299710}, {0xc53280, 0xc0002994a0}}, {0xea33b8, 0xc000100370}}, 0xc000124b88, ...}, ...)
        github.com/cockroachdb/terraform-provider-cockroach/internal/provider/cluster_resource.go:441 +0x665
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc0003f4160, {0xe9d680, 0xc0004dd8f0}, 0xc0004dd9e0, 0xc0002b1608)
        github.com/hashicorp/terraform-plugin-framework@v1.1.1/internal/fwserver/server_readresource.go:97 +0x60e
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0xc0003f4160, {0xe9d680?, 0xc0004dd7a0?}, 0xc000128380)
        github.com/hashicorp/terraform-plugin-framework@v1.1.1/internal/proto6server/server_readresource.go:52 +0x27b
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc00030f7c0, {0xe9d680?, 0xc0004dcff0?}, 0xc000516780)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/tf6server/server.go:746 +0x49e
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0xd1e7a0?, 0xc00030f7c0}, {0xe9d680, 0xc0004dcff0}, 0xc00017acb0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0xea13e0, 0xc000416680}, 0xc0004d7560, 0xc0003f71d0, 0x13b9290, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0xea13e0, 0xc000416680}, 0xc0004d7560, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-cockroach_v0.6.0 plugin crashed!```

**Comment by jaylim-crl** [comment]
Thanks for the bug report. I noticed the same thing while trying to import a cluster as well. This should be fixed once a new provider version has been released.
